name: vca
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - astor=0.8.1=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h1ea3ea9_openblas
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - gast=0.5.5=pyhd8ed1ab_0
  - grpcio=1.46.3=py37he500948_0
  - h5py=3.7.0=nompi_py37hf1ce037_101
  - hdf5=1.12.2=nompi_h2386368_101
  - importlib-metadata=4.11.4=py37h89c1867_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - ipython=7.33.0=py37h89c1867_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.3=h58526e2_2
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.8.0=h8b12597_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libzlib=1.2.13=h4ab18f5_6
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mock=5.1.0=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.21.6=py37h976b520_0
  - openblas=0.3.30=pthreads_h6ec200e_3
  - openssl=1.1.1w=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - protobuf=3.8.0=py37he1b5a44_2
  - psutil=5.9.3=py37h540881e_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.7.13=haa1d7c7_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - readline=8.2=h8c095d6_2
  - scipy=1.7.3=py37hf838250_2
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tensorboard=1.13.1=py37_0
  - tensorflow=1.13.1=h5ece82f_5
  - tensorflow-base=1.13.1=py37h5ece82f_5
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.2=py37h540881e_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6

